### PR TITLE
migrate to Angular latest and fix two way data bindings on form

### PR DESCRIPTION
**Pull request by antonymarion**
cf https://github.com/emqx/MQTT-Client-Examples/issues/140

I migrated also to latest Angular version and added some toast to help debugging/troubleshooting.

I bumped ngx-mqtt client lib too.

### CODE REVIEW

**Comment by ysfscream** [comment]
Hi, @antonymarion Thank you very much for your contribution to the update.

However, it seems like the version upgrade is quite significant, and our related blog content cannot be updated in time. I recommend not directly modifying the project to ensure users can easily find code compatible with their current version. If possible, could you please separate the two versions into different folders? This way, users can choose the version they need for reference according to their requirements. Thank you very much! 🙏

**Comment by antonymarion** [comment]
Of course, I have also a capacitor version using native plugins from the community to test eqmx broker. 

I can provide you another directory for this one too if you think this is of interest.

**Review by ysfscream — APPROVED** [review]

**Comment by zibuyu1995** [comment]
@ysfscream Could we merge this PR?

**Comment by ysfscream** [comment]
@zibuyu1995 Not yet. This change affects the old version's code examples, but we need to keep those and create a new folder to include these changes.

@antonymarion Thanks for your work. However, this has been stagnant for a long time. Can we modify the new Angular 17 to a new folder, as suggested, without affecting the old code? If this cannot be completed, I will close this PR.

**Comment by ysfscream** [comment]
@antonymarion Thanks for your response, I will close this issue. and submit the New One.

**Pull request closed without merging**
